# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3000a88c20a300bd17faefb4ab7e774fed13842a0e20c5cd0dd3c5ddf13481d1bdaf245ac158a45c59deca752ca6f14eff43bc49c950fb28ab91cce1b19667ab

test:
  secret_key_base: e362cd76b8bc39b9d1f94acdfe9bdbf3143c7cf2e32d0880ea7048706ebb0356abdcaa78844a5960071603811d7429ffe9e0f7249378e82e7785c7f66a6d6d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
